---
hero_image: images / banner.png
theme: Armada
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, diseño-0, programación-1, phys-comp-0, fabricación-0, comunidad-0
title: Generador de poesía de Ada
description: '¡Celebre Ada Lovelace Day, aprendiendo cómo programar su propio generador de poesía!'
original_url: https://codeclubprojects.org/en-GB/scratch/poetry-generator
interests: literatura
technologies: rasguño
site_areas: proyectos
hardware: ''
software: rasguño
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Ada Lovelace
  - 
    title: 'Desafío: Codifique a Ada para presentarse'
  - 
    title: Diciéndole a Ada tu nombre
  - 
    title: El motor analítico
  - 
    title: Más poesía
  - 
    title: Animar el motor analítico
  - 
    title: 'Desafío: personaliza tu poema'
  - 
    title: 'Desafío: Más palabras'
  - 
    title: 'Desafío: más poesía'
