---
hero_image: imatges / banner.png
theme: marina
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, disseny-0, programació-1, phys-comp-0, fabricació-0, comunitat-0
title: Generador de poesia d'Ada
description: Celebreu el Dia Ada Lovelace, aprenent a programar el vostre propi generador de poesia.
original_url: https://codeclubprojects.org/en-GB/scratch/poetry-generator
interests: literatura
technologies: rascar
site_areas: projectes
hardware: ''
software: rascar
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Ada Lovelace
  - 
    title: 'Desafiament: Codi Ada per presentar-se'
  - 
    title: Digueu a Ada el vostre nom
  - 
    title: El motor analític
  - 
    title: Més poesia
  - 
    title: Animació del motor analític
  - 
    title: 'Desafiament: personalitzeu el vostre poema'
  - 
    title: 'Desafiament: més paraules'
  - 
    title: 'Desafiament: més poesia'
